name: settings_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  drift: ^2.18.0
  drift_flutter: ^0.1.0
  flutter:
    sdk: flutter
  isar: any
  isar_flutter_libs: any
  isar_generator: any
  rxdart: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  build_runner: any
  drift_dev: ^2.18.0
