name: razor_expense_tracker_new
description: "An AI powered Expense Tracker"
version: 1.0.0+1
publish_to: 'none'


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  fl_chart: ^0.68.0
  flutter_localizations:
    sdk: flutter
  intl: any
  local_storage_transactions_api:
    path: packages/local_storage_transactions_api
  transactions_api:
    path: packages/transactions_api
  transactions_repository:
    path: packages/transactions_repository
  logger: ^2.2.0
  material_symbols_icons: ^4.2719.3
  url_launcher: ^6.2.6
  path_provider: any
  uuid: ^4.4.0
  flutter_slidable: ^3.1.0
  string_validator: ^1.1.0
  easy_localization: ^3.0.7



dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  mockingjay: ^0.5.0
  very_good_analysis: ^5.1.0


flutter:
  assets:
    - assets/translations/
  uses-material-design: true
  generate: true