name: transactions_api
description: The interface and models for an API providing access to transactions.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  analyzer: ^5.13.0
  font_awesome_flutter: any
  intl: 0.19.0
  isar: any
  isar_flutter_libs: any
  isar_generator: any
  logger: ^2.3.0
  uuid: ^4.4.0




dev_dependencies:
  build_runner: ^2.2.0
  equatable: 2.0.3
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
