name: transactions_repository
description: A repository that handles transaction related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
dependencies:
  logger: ^2.2.0
  transactions_api:
    path: ../transactions_api
dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
