name: local_storage_transactions_api
description: A Flutter implementation of the TransactionsApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  meta: ^1.11.0
  rxdart: ^0.27.5
  transactions_api:
    path: ../transactions_api
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
