name: drift_database_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  material_symbols: ^0.0.0
  material_symbols_icons: ^4.2771.0
  rxdart: ^0.28.0
  transactions_api:
    path: ../transactions_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
